#199 integrate email templates in the portal for sign up and forgot password
SciLifeLab-TrainingHub-Platform/TeSS pull request #222
Opened 2024-12-03 10:13 UTC by adeel-ahmad-awan

# In progress (do not merge)
----
**Ticket**

- [199 integrate email templates in the portal for sign up and forgot password](https://app.zenhub.com/workspaces/th-developmentdesigning-board-6565ea6f792dae0625b5c739/issues/gh/scilifelab-traininghub-platform/tess/199)

2024-12-18 10:20 UTC, harshita3199 commented
@adeel-ahmad-awan Could you please remove the .(dot) in training.hub@scilifelab.se mail in the footer so that it looks as **traininghub@scilifelab.se** 
Also, instead of the email ID in the **signup confirmation** and **<img width="710" alt="Screenshot 2024-12-18 at 11 13 05 AM" src="https://github.com/user-attachments/assets/72e9cbda-aa38-4b42-997b-618cb6014a64" />** mail, could we have the name in the template
![image](https://github.com/user-attachments/assets/df9cbb1a-e7f7-40fd-bde7-3f3cd1e6608c)

2024-12-18 14:38 UTC, umunixie requested changes
overall looks fine, just a couple of details raised questions

2024-12-18 14:38 UTC, umunixie commented on test/mailers/previews/devise_mailer_preview.rb
> +  # def unlock_instructions
i don't quite understand why we're committing commented out code here

2024-12-18 14:38 UTC, umunixie commented on app/views/layouts/mailer.html.erb
> +        <a href="mailto:training.hub@scilifelab.se" style="font-size: 14px; color: #045C64; text-decoration: none;">training.hub@scilifelab.se</a>
is there a way to not hardcode this email address in multiple places?

2024-12-19 13:46 UTC, adeel-ahmad-awan commented on test/mailers/previews/devise_mailer_preview.rb
> +  # def unlock_instructions
its just like if we need the other email templates, the code is already there

2024-12-20 09:47 UTC, umunixie approved these changes

2025-01-27 15:20 UTC, adeel-ahmad-awan commented
testing

2025-01-28 09:48 UTC, harshita3199 commented
Need to test this ticket

2025-02-19 14:44 UTC, harshita3199 commented
This PR is tested and all the emails are getting triggered properly, hence merging the PR

2025-02-19 14:45 UTC, merged