added STO title and updated system developer title
SciLifeLab-TrainingHub-Platform/TeSS pull request #6
Opened 2023-11-29 17:51 UTC by ninanorgren

**Summary of changes**

Fix issue https://app.asana.com/0/1205707359650184/1206055942700380/f 
- Added STO titles to remaining
- Updated to System Developer

2023-11-29 18:02 UTC, ninanorgren commented
Accidentally pushed changes for another issue to this branch also, https://app.asana.com/0/1205707359650184/1206055942392457/f 

Resized the pedagogic support box so the text does not overflow

2023-11-30 09:28 UTC, harshita3199 commented on app/views/about/us.html.erb
> +                <div class="image-header">Scientific Training Officers</div>
remove 's' from Officers to Scientific Training Officer

2023-11-30 09:28 UTC, harshita3199 commented on app/views/about/us.html.erb
> +                <div class="image-header">Scientific Training Officers</div>
Scientific Training Officer

2023-11-30 09:29 UTC, harshita3199 requested changes
Added the comments to just change from Officers to 'Officer'

2023-12-01 09:22 UTC, harshita3199 approved these changes
Approved

2023-12-01 09:23 UTC, merged